services:
  - type: web
    name: seongdong-marketing-helper
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    healthCheckPath: /health
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: FLASK_ENV
        value: production
      - key: WEB_CONCURRENCY
        value: "1"
      - key: PYTHONUNBUFFERED
        value: "1"
