services:
  - type: web
    name: seongdong-marketing-helper
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 2 --timeout 60 --graceful-timeout 30 --max-requests 50 --max-requests-jitter 10 --keep-alive 15 --access-logfile - --error-logfile - --log-level info --preload
    healthCheckPath: /health
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: FLASK_ENV
        value: production
